### ISSUE TITLE
moon.lua Issue

### ISSUE THREAD

**Issue by rokf** [leafo/moonscript-textadept#1]
Getting `unexpected symbol near '<'`on line 9.

What should `<<` even mean?

**Comment by leafo** [comment]
What version of textadept are you using? I'm on the most recent, which uses Lua 5.3, which has bitwise operators built into the language.

**Comment by rokf** [comment]
Oh, I was running the `textadeptjit` executable and thats why it did not work.

**Comment by leafo** [comment]
hmm, I didn't realize `textadeptjit` was a thing. I definitely think it should support both in that case.
